<?php

return [
    'fuutarou' => [
        'slug' => 'fuutarou',
        'order' => 0,
        'kanji' => '上杉 風太郎',
        'romaji' => 'Fuutarou Uesugi',
        'hiragana' => 'うえすぎ ふうたろう',
        'cv' => [
            'ja' => 'CV：松岡禎丞',
            'id' => 'CV: Yoshitsugu Matsuoka',
            'en' => 'CV: Yoshitsugu Matsuoka',
        ],
        'role_label' => [
            'ja' => '主人公・家庭教師',
            'id' => 'Tokoh Utama • Guru Privat',
            'en' => 'Protagonist • Private Tutor',
        ],
        'tab_sub' => [
            'ja' => '主人公',
            'id' => 'Tokoh Utama',
            'en' => 'Protagonist',
        ],
        'gallery_tag' => [
            'ja' => '秀才 × 家庭教師',
            'id' => 'Siswa Jenius × Guru Privat',
            'en' => 'Genius Student × Tutor',
        ],
        'quote' => [
            'ja' => '「俺がお前たちを絶対に全員卒業させてやる！」',
            'id' => '「Aku pasti akan membimbing kalian berlima sampai lulus!」',
            'en' => '「I will definitely make sure every single one of you graduates!」',
        ],
        'description' => [
            'ja' => '本作の主人公。学年トップの成績を誇る極めて優秀な高校生。家の多額の借金を返済するため、破格の報酬で中野家の家庭教師を引き受ける。社交性は低く不器用だが、５つ子たちのために真摯に全力を尽くす。',
            'id' => 'Protagonis utama. Siswa SMA jenius yang selalu menduduki peringkat pertama. Mengambil pekerjaan guru privat bergaji tinggi untuk melunasi hutang keluarganya. Meski awalnya canggung dan kaku, ia selalu tulus membantu 5 saudari kembar Nakano.',
            'en' => 'The protagonist of the story. A brilliant high school student who consistently achieves perfect scores. To help pay off his family\'s debt, he becomes the private tutor for the quintuplets, working tirelessly to earn their trust and guide them to graduation.',
        ],
        'subject' => [
            'ja' => '全教科 100点 (全科目得意)',
            'id' => 'Semua Pelajaran (Nilai 100)',
            'en' => 'All Subjects (Perfect 100s)',
        ],
        'food' => [
            'ja' => '焼肉定食・うどん',
            'id' => 'Yakiniku Teishoku / Udon',
            'en' => 'Yakiniku Set Meal / Udon',
        ],
        'trait' => [
            'ja' => '黒髪 ＆ いつも勉強道具を所持',
            'id' => 'Rambut Hitam & Selalu Membawa Buku',
            'en' => 'Dark Hair & Always Carrying Study Books',
        ],
        'image' => 'images/fuutarou.jpg',
        'fallback_image' => 'https://cdn.myanimelist.net/images/characters/16/374828.jpg',
        'theme' => [
            'color' => 'indigo',
            'bg_light' => 'bg-indigo-50',
            'bg_light_hover' => 'hover:bg-indigo-100',
            'border' => 'border-indigo-400',
            'border_light' => 'border-indigo-200',
            'border_dark' => 'border-indigo-600',
            'text' => 'text-indigo-600',
            'text_dark' => 'text-indigo-900',
            'badge_bg' => 'bg-indigo-100',
            'badge_text' => 'text-indigo-800',
            'badge_solid' => 'bg-indigo-600 text-white',
            'gradient' => 'from-indigo-600 via-indigo-700 to-slate-800',
            'quote_bg' => 'bg-indigo-50',
            'quote_border' => 'border-indigo-500',
            'accent_hex' => '#4f46e5',
            'dark_hex' => '#3730a3',
        ],
    ],
    'ichika' => [
        'slug' => 'ichika',
        'order' => 1,
        'kanji' => '中野 一花',
        'romaji' => 'Ichika Nakano',
        'hiragana' => 'なかの いちか',
        'cv' => [
            'ja' => 'CV：花澤香菜',
            'id' => 'CV: Kana Hanazawa',
            'en' => 'CV: Kana Hanazawa',
        ],
        'role_label' => [
            'ja' => '長女 (First Sister)',
            'id' => 'Anak Pertama (Kakak Sulung)',
            'en' => 'First Sister (Eldest)',
        ],
        'tab_sub' => [
            'ja' => '長女',
            'id' => 'Anak ke-1',
            'en' => '1st Sister',
        ],
        'gallery_tag' => [
            'ja' => 'お姉さん × 女優',
            'id' => 'Kakak Sulung × Aktris',
            'en' => 'Big Sister × Aspiring Actress',
        ],
        'quote' => [
            'ja' => '「お姉さんだからね。みんなの面倒はちゃんと見るよ」',
            'id' => '「Karena aku anak tertua, aku pasti akan menjaga adik-adikku dengan baik」',
            'en' => '「I\'m the oldest sister, so of course I\'ll look after everyone.」',
        ],
        'description' => [
            'ja' => '５つ子の長女。面倒見の良いお姉さん気質だが、部屋の中ではかなりズボラ。駆け出しの女優としても活動しており、姉妹たちの恋の行方を温かく見守りつつ、自身も風太郎に惹かれていく。',
            'id' => 'Anak pertama dari 5 bersaudara kembar. Memiliki sifat keibuan dan suka merawat adik-adiknya, meski di rumah sendiri kamarnya sangat berantakan. Bekerja sebagai aktris pemula dan perlahan jatuh hati pada Fuutarou.',
            'en' => 'The eldest of the quintuplets. She has a caring and mature personality, although she is notoriously messy at home. She works as an aspiring actress and gradually develops feelings for Fuutarou.',
        ],
        'subject' => [
            'ja' => '数学',
            'id' => 'Matematika',
            'en' => 'Mathematics',
        ],
        'food' => [
            'ja' => 'フラペチーノ',
            'id' => 'Frappuccino',
            'en' => 'Frappuccino',
        ],
        'trait' => [
            'ja' => 'ショートヘア ＆ ピアス',
            'id' => 'Rambut Pendek & Anting',
            'en' => 'Short Hair & Earrings',
        ],
        'image' => 'images/ichika.jpg',
        'fallback_image' => 'https://cdn.myanimelist.net/images/characters/9/374823.jpg',
        'theme' => [
            'color' => 'amber',
            'bg_light' => 'bg-amber-50',
            'bg_light_hover' => 'hover:bg-amber-100',
            'border' => 'border-amber-400',
            'border_light' => 'border-amber-200',
            'border_dark' => 'border-amber-600',
            'text' => 'text-amber-600',
            'text_dark' => 'text-amber-900',
            'badge_bg' => 'bg-amber-100',
            'badge_text' => 'text-amber-800',
            'badge_solid' => 'bg-amber-500 text-white',
            'gradient' => 'from-amber-400 to-yellow-200',
            'quote_bg' => 'bg-amber-50',
            'quote_border' => 'border-amber-400',
            'accent_hex' => '#f59e0b',
            'dark_hex' => '#b45309',
        ],
    ],
    'nino' => [
        'slug' => 'nino',
        'order' => 2,
        'kanji' => '中野 二乃',
        'romaji' => 'Nino Nakano',
        'hiragana' => 'なかの にの',
        'cv' => [
            'ja' => 'CV：竹達彩奈',
            'id' => 'CV: Ayana Taketatsu',
            'en' => 'CV: Ayana Taketatsu',
        ],
        'role_label' => [
            'ja' => '次女 (Second Sister)',
            'id' => 'Anak Kedua (Second Sister)',
            'en' => 'Second Sister',
        ],
        'tab_sub' => [
            'ja' => '次女',
            'id' => 'Anak ke-2',
            'en' => '2nd Sister',
        ],
        'gallery_tag' => [
            'ja' => 'ツンデレ × 料理上手',
            'id' => 'Tsundere × Jago Masak',
            'en' => 'Tsundere × Master Cook',
        ],
        'quote' => [
            'ja' => '「あんたのことなんか全然認めてないんだからね！」',
            'id' => '「Bukannya aku sudah menerima keberadaanmu ya!」',
            'en' => '「It\'s not like I\'ve acknowledged you or anything!」',
        ],
        'description' => [
            'ja' => '５つ子の次女。姉妹の中で最も繊細で家族思いなツンデレ。料理が得意で女子力が一番高い。最初は風太郎を強く警戒していたが、一度心を開いてからは一番積極的で情熱的なアプローチを見せる。',
            'id' => 'Anak kedua dari 5 bersaudara kembar. Gadis tsundere yang paling peduli dan melindungi keluarganya. Paling pandai memasak dan fashionable. Setelah membuka hatinya, dia adalah yang paling berani dan agresif mengungkapkan perasaannya.',
            'en' => 'The second sister. Highly protective of her family with a sharp tsundere personality. She is the best cook among the sisters and very fashionable. Once she falls in love, she is the most straightforward and passionate.',
        ],
        'subject' => [
            'ja' => '英語',
            'id' => 'Bahasa Inggris',
            'en' => 'English',
        ],
        'food' => [
            'ja' => 'パンケーキ',
            'id' => 'Pancake',
            'en' => 'Pancakes',
        ],
        'trait' => [
            'ja' => '黒リボン ＆ ツインテール',
            'id' => 'Pita Hitam & Twintail',
            'en' => 'Black Ribbon & Twin Tails',
        ],
        'image' => 'images/nino.jpg',
        'fallback_image' => 'https://cdn.myanimelist.net/images/characters/11/374824.jpg',
        'theme' => [
            'color' => 'purple',
            'bg_light' => 'bg-purple-50',
            'bg_light_hover' => 'hover:bg-purple-100',
            'border' => 'border-purple-400',
            'border_light' => 'border-purple-200',
            'border_dark' => 'border-purple-600',
            'text' => 'text-purple-600',
            'text_dark' => 'text-purple-900',
            'badge_bg' => 'bg-purple-100',
            'badge_text' => 'text-purple-800',
            'badge_solid' => 'bg-purple-600 text-white',
            'gradient' => 'from-purple-500 to-pink-300',
            'quote_bg' => 'bg-purple-50',
            'quote_border' => 'border-purple-400',
            'accent_hex' => '#a855f7',
            'dark_hex' => '#7e22ce',
        ],
    ],
    'miku' => [
        'slug' => 'miku',
        'order' => 3,
        'kanji' => '中野 三玖',
        'romaji' => 'Miku Nakano',
        'hiragana' => 'なかの みく',
        'cv' => [
            'ja' => 'CV：伊藤美来',
            'id' => 'CV: Miku Ito',
            'en' => 'CV: Miku Ito',
        ],
        'role_label' => [
            'ja' => '三女 (Third Sister)',
            'id' => 'Anak Ketiga (Third Sister)',
            'en' => 'Third Sister',
        ],
        'tab_sub' => [
            'ja' => '三女',
            'id' => 'Anak ke-3',
            'en' => '3rd Sister',
        ],
        'gallery_tag' => [
            'ja' => 'クール × 戦国武将',
            'id' => 'Pendiam × Penggemar Panglima Perang',
            'en' => 'Quiet × Sengoku Period Fan',
        ],
        'quote' => [
            'ja' => '「責任取ってよね。私を好きにさせた責任」',
            'id' => '「Kamu harus bertanggung jawab... karena telah membuatku menyukaimu.」',
            'en' => '「Take responsibility... for making me fall in love with you.」',
        ],
        'description' => [
            'ja' => '５つ子の三女。口数が少なく物静かだが、内に熱い想いを秘める。大の戦国武将好き。自分に自信が持てなかったが、風太郎に認められたい一心で料理や勉強にひたむきに努力する。',
            'id' => 'Anak ketiga dari 5 bersaudara kembar. Pendiam dan pemalu, namun memiliki kegemaran rahasia terhadap jenderal perang zaman Sengoku. Berkat bimbingan Fuutarou, dia terus berusaha keras belajar dan memasak agar diakui.',
            'en' => 'The third sister. Quiet, reserved, and low on self-confidence at first, with a hidden passion for Sengoku warlords. Inspired by Fuutarou, she works tirelessly to master cooking and improve her grades.',
        ],
        'subject' => [
            'ja' => '社会 (日本史)',
            'id' => 'Ilmu Sosial (Sejarah Jepang)',
            'en' => 'Social Studies (Japanese History)',
        ],
        'food' => [
            'ja' => '抹茶 ＆ 緑茶',
            'id' => 'Matcha & Teh Hijau',
            'en' => 'Matcha & Green Tea',
        ],
        'trait' => [
            'ja' => '青いヘッドホン ＆ セミロング',
            'id' => 'Headphone Biru & Rambut Sedang',
            'en' => 'Blue Headphones & Medium Hair',
        ],
        'image' => 'images/miku.jpg',
        'fallback_image' => 'https://cdn.myanimelist.net/images/characters/12/374825.jpg',
        'theme' => [
            'color' => 'sky',
            'bg_light' => 'bg-sky-50',
            'bg_light_hover' => 'hover:bg-sky-100',
            'border' => 'border-sky-400',
            'border_light' => 'border-sky-200',
            'border_dark' => 'border-sky-600',
            'text' => 'text-sky-600',
            'text_dark' => 'text-sky-900',
            'badge_bg' => 'bg-sky-100',
            'badge_text' => 'text-sky-800',
            'badge_solid' => 'bg-sky-600 text-white',
            'gradient' => 'from-sky-500 to-cyan-200',
            'quote_bg' => 'bg-sky-50',
            'quote_border' => 'border-sky-400',
            'accent_hex' => '#0284c7',
            'dark_hex' => '#0369a1',
        ],
    ],
    'yotsuba' => [
        'slug' => 'yotsuba',
        'order' => 4,
        'kanji' => '中野 四葉',
        'romaji' => 'Yotsuba Nakano',
        'hiragana' => 'なかの よつば',
        'cv' => [
            'ja' => 'CV：佐倉綾音',
            'id' => 'CV: Ayane Sakura',
            'en' => 'CV: Ayane Sakura',
        ],
        'role_label' => [
            'ja' => '四女 (Fourth Sister)',
            'id' => 'Anak Keempat (Fourth Sister)',
            'en' => 'Fourth Sister',
        ],
        'tab_sub' => [
            'ja' => '四女',
            'id' => 'Anak ke-4',
            'en' => '4th Sister',
        ],
        'gallery_tag' => [
            'ja' => '天真爛漫 × スポーツ',
            'id' => 'Ceria × Atletis',
            'en' => 'Energetic × Athletic Star',
        ],
        'quote' => [
            'ja' => '「上杉さん！私にできることなら何でも言ってください！」',
            'id' => '「Uesugi-san! Katakan apa saja jika ada yang bisa kubantu!」',
            'en' => '「Uesugi-san! If there\'s anything I can do to help, just say the word!」',
        ],
        'description' => [
            'ja' => '５つ子の四女。いつも明るく元気いっぱいで、他人の頼み事を絶対に断れないお人好し。運動神経抜群で様々な運動部の助っ人として大活躍。風太郎を最初から全力で応援してくれる唯一の味方。',
            'id' => 'Anak keempat dari 5 bersaudara kembar. Selalu ceria, energik, dan tidak pernah bisa menolak permintaan bantuan orang lain. Memiliki kemampuan atletik luar biasa dan selalu mendukung Fuutarou sejak awal.',
            'en' => 'The fourth sister. Always cheerful, enthusiastic, and unable to say no to anyone asking for help. Extremely athletic, she is Fuutarou\'s first and most supportive ally from day one.',
        ],
        'subject' => [
            'ja' => '国語',
            'id' => 'Bahasa (Sastra)',
            'en' => 'Japanese Literature',
        ],
        'food' => [
            'ja' => 'みかん ＆ カレー',
            'id' => 'Jeruk Mandarin & Kari',
            'en' => 'Mandarin Oranges & Curry',
        ],
        'trait' => [
            'ja' => '緑のリボンカチューシャ',
            'id' => 'Bando Pita Hijau',
            'en' => 'Green Ribbon Headband',
        ],
        'image' => 'images/yotsuba.jpg',
        'fallback_image' => 'https://cdn.myanimelist.net/images/characters/2/374826.jpg',
        'theme' => [
            'color' => 'green',
            'bg_light' => 'bg-green-50',
            'bg_light_hover' => 'hover:bg-green-100',
            'border' => 'border-green-400',
            'border_light' => 'border-green-200',
            'border_dark' => 'border-green-600',
            'text' => 'text-green-600',
            'text_dark' => 'text-green-900',
            'badge_bg' => 'bg-green-100',
            'badge_text' => 'text-green-800',
            'badge_solid' => 'bg-green-600 text-white',
            'gradient' => 'from-green-500 to-emerald-200',
            'quote_bg' => 'bg-green-50',
            'quote_border' => 'border-green-400',
            'accent_hex' => '#22c55e',
            'dark_hex' => '#15803d',
        ],
    ],
    'itsuki' => [
        'slug' => 'itsuki',
        'order' => 5,
        'kanji' => '中野 五月',
        'romaji' => 'Itsuki Nakano',
        'hiragana' => 'なかの いつき',
        'cv' => [
            'ja' => 'CV：水瀬いのり',
            'id' => 'CV: Inori Minase',
            'en' => 'CV: Inori Minase',
        ],
        'role_label' => [
            'ja' => '五女 (Fifth Sister)',
            'id' => 'Anak Kelima (Fifth Sister)',
            'en' => 'Fifth Sister (Youngest)',
        ],
        'tab_sub' => [
            'ja' => '五女',
            'id' => 'Anak ke-5',
            'en' => '5th Sister',
        ],
        'gallery_tag' => [
            'ja' => '生真面目 × 食いしん坊',
            'id' => 'Serius × Doyan Makan (Eatsuki)',
            'en' => 'Earnest × Foodie Lover',
        ],
        'quote' => [
            'ja' => '「私だって…誰よりも頑張って母のような先生になりたいんです」',
            'id' => '「Aku juga... ingin berusaha lebih keras agar bisa menjadi guru seperti ibu!」',
            'en' => '「I want to work harder than anyone to become a teacher just like my mother.」',
        ],
        'description' => [
            'ja' => '５つ子の五女。生真面目で不器用な努力家。亡き母の教えを胸に教師を目指す。大食いで美味しいもの（特に肉まんやカレー）に目がない。風太郎とは最悪の出会いだったが、最も深い信頼関係を築く。',
            'id' => 'Anak kelima dari 5 bersaudara kembar. Sangat disiplin, berdedikasi, dan bercita-cita menjadi guru seperti mendiang ibunya. Sangat suka makan (terutama bakpao daging dan kari). Membangun rasa saling percaya yang sangat mendalam dengan Fuutarou.',
            'en' => 'The youngest quintuplet. Earnest, serious, and hardworking with dreams of becoming a teacher. A passionate foodie who loves meat buns and curry. She develops a profound bond of mutual trust with Fuutarou.',
        ],
        'subject' => [
            'ja' => '理科',
            'id' => 'Ilmu Pengetahuan Alam (Sains)',
            'en' => 'Science',
        ],
        'food' => [
            'ja' => '肉まん ＆ カレーライス',
            'id' => 'Nikuman (Bakpao) & Nasi Kari',
            'en' => 'Meat Buns & Curry Rice',
        ],
        'trait' => [
            'ja' => '星型ヘアピン ＆ アホ毛',
            'id' => 'Jepit Bintang & Ahoge',
            'en' => 'Star Hairpins & Ahoge',
        ],
        'image' => 'images/itsuki.jpg',
        'fallback_image' => 'https://cdn.myanimelist.net/images/characters/10/374827.jpg',
        'theme' => [
            'color' => 'red',
            'bg_light' => 'bg-red-50',
            'bg_light_hover' => 'hover:bg-red-100',
            'border' => 'border-red-400',
            'border_light' => 'border-red-200',
            'border_dark' => 'border-red-600',
            'text' => 'text-red-600',
            'text_dark' => 'text-red-900',
            'badge_bg' => 'bg-red-100',
            'badge_text' => 'text-red-800',
            'badge_solid' => 'bg-red-600 text-white',
            'gradient' => 'from-red-500 to-rose-200',
            'quote_bg' => 'bg-red-50',
            'quote_border' => 'border-red-400',
            'accent_hex' => '#ef4444',
            'dark_hex' => '#b91c1c',
        ],
    ],
];
